# Generated by Django 2.1.7 on 2019-05-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('easy', '初级'), ('ordinary', '中级'), ('advanced', '高级')], default='', max_length=20, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='课程时长'),
        ),
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.CharField(default='', max_length=300, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='课程名称'),
        ),
    ]
