# Generated by Django 2.1.7 on 2019-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_chapter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', max_length=300, verbose_name='课程描述'),
        ),
    ]
