# Generated by Django 2.1.7 on 2019-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190530_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notice',
            field=models.TextField(default='', max_length=300, verbose_name='课程须知'),
        ),
    ]
